### ISSUE TITLE
Add CRUD for exercises

### ISSUE THREAD

**Issue by anton-moskalenko** [anton-moskalenko/rune#1]
# Tasks

- [x] Add read collection
  - [x] Rename API method block (area -> exercises).
- [x] Add read entity
  - [x] Add exercises manager load method.
  - [x] Add Exercises.Load API method.
  - [x] Add Exercises.Load API method request
- [x] Add update entity
  - [x] Add Exercises.Load API method
- [x] Add delete entity (do not do - we don't actually remove exercises - only change status to absolete)
- [x] Add create entity
- [x] Review
